//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ParentName { get; set; }
        public string ParentContact { get; set; }
        public string ParentEmail { get; set; }
        public string Class { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> SchoolId { get; set; }
    
        public virtual School School { get; set; }
    }
}
