//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetention
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int DetentionId { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Duration { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DetentionActionId { get; set; }
    }
}
